name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: "0 12 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: 'all_time'
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          CODE_LANG: dart
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
            #committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: hatch01
          template: classic
          base: header, activity, community, repositories #, metadata
          config_animations: yes
          config_timezone: Europe/Paris
          optimize: no
          #repositories_forks: yes
          use_prebuilt_image: yes

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: explorer, infographile, member, worker, verified
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_skipped: GOD-GOG
          plugin_lines: yes
          #plugin_notable: yes
          #plugin_notable_filter: stars:>100
          #plugin_notable_repositories: yes
          plugin_repositories: yes
          plugin_repositories_featured: onyx-lyon1/onyx
          #plugin_topics: yes
          #plugin_topics_mode: mastered
          #plugin_topics_limit: 20
          plugin_traffic: yes          
